#pragma config(Motor,  port2,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           pipeServo,     tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		if(vexRT[Btn8D]){
			if(abs(vexRT[Ch3]) > 10){
				motor[port2] = vexRT[Ch3];
				motor[port3] = -vexRT[Ch3];
			} else {
				motor[port2] = 0;
				motor[port3] = 0;
			}
		} else if(vexRT[Btn7D]){
			if(abs(vexRT[Ch1]) > 10){
				motor[port2] = vexRT[Ch1];
				motor[port3] = vexRT[Ch1];
			} else {
				motor[port2] = 0;
				motor[port3] = 0;
			}
		} else {
			if(abs(vexRT[Ch2]) > 10){
				motor[port3] = -vexRT[Ch2];
			}
			else {
				motor[port3] = 0;
			}
			if(abs(vexRT[Ch3]) > 10){
				motor[port2] = vexRT[Ch3];
			}
			else {
				motor[port2] = 0;
			}
		}
		if(vexRT[Btn5U]){
			motor[port4] = -50;
		}
		if(vexRT[Btn5D]){
			motor[port4] = 127;
		}
	}

}
